version: '3.5'

services:
  nuxt:
    build:
      context: .
    image: next-app
    container_name: next-app
    ports:
      - ${OUTPUT_PORT}:3000

# Remember to see the pages on port OUTPUT_PORT in .env
