version: '3.5'

services:
  nextjs:
    build:
      context: .
    image: nextjs-app
    container_name: nextjs-app
    ports:
      - ${OUTPUT_PORT}:3000

# Remember to see the pages on port OUTPUT_PORT in .env
